on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
      - name: Build with Maven
        run: mvn clean install
      - name: Create Release
        run: |
          curl --request POST "${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/releases" \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header "Accept: application/vnd.github.v3+json" \
          -d "
          {
            \"tag_name\": \"${GITHUB_REF_NAME}\",
            \"body\": \"# test\",
            \"generate_release_notes\": true
          }
          "
